version: 2.1

jobs:
  # create_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli

  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:["79:42:fc:f3:b5:36:c6:73:8e:f1:ef:32:82:09:bd:94"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure Server
          command: |
            ansible-playbook -i inventory main.yml
      

workflows:
  myWorkflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
