version: 2.1

jobs:
  check_aws_credentials:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: check aws credentials
          command: env | grep AWS

  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws configure set aws_session_token ""
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

workflows:
  myWorkflow:
    jobs:
      - check_aws_credentials
      - create_infrastructure
