version: 2.1

commands:
  destroy_environment:
    parameters:
      when:
        type: string
    steps:
      - run:
          name: Destroy Environment
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["79:42:fc:f3:b5:36:c6:73:8e:f1:ef:32:82:09:bd:94"]
      - run:
          name: install ssh
          command: |
            apk add openssh

      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure Server
          command: |
            ssh-keyscan -H 54.146.175.123 >> ~/.ssh/known_hosts
            ansible-playbook -i inventory main.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: Smoke Test
          command: |
            URL="https://blog.udacity.com"
            if curl -s --head ${URL}
            then
              return 1
            else
              return 0
            fi
      - destroy_environment:
          when: "on_fail"

workflows:
  myWorkflow:
    jobs:
      # - create_infrastructure
      # - configure_infrastructure
      - smoke_test
